name: template-pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
      

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet version
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --no-restore --blame-hang --blame-hang-timeout 60s /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverage' /p:Include='[MudBlazor]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'
      - name: ls
        if: always()
        run: |
            ls -la
            ls -la MudBlazor
            find . -name 'coverage*' -print 
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-artifact
          path: MudBlazor.UnitTests/TestResults
      - name: Coverage
        if: ${{ inputs.publish-coverage == true }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.cobertura.xml

      - uses: actions/upload-artifact@v2
        if: ${{ inputs.deploy-web-app == true }}
        with:
          name: ${{ inputs.deploy-web-app-name }}
          path: ${{env.DOTNET_ROOT}}/${{ inputs.deploy-web-app-name }}
  
